[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "=1.4.0"